"""initial ledger schema

Revision ID: 656deaa29f37
Revises:
Create Date: 2026-08-08 12:04:01.106227

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "656deaa29f37"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_categories_user_slug"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index("ix_categories_user", ["user_id"], unique=False)

    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("merchant_tz", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_merchants_user_slug"),
    )
    with op.batch_alter_table("merchants", schema=None) as batch_op:
        batch_op.create_index("ix_merchants_user", ["user_id"], unique=False)

    op.create_table(
        "raw_extractions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("image_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "TELEGRAM_IMAGE", "TELEGRAM_PDF", "TELEGRAM_TEXT", name="source", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_micros_usd", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_extractions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_raw_extractions_user_hash", ["user_id", "image_sha256"], unique=False
        )

    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("raw_extraction_id", sa.String(length=36), nullable=True),
        sa.Column("merchant_id", sa.String(length=36), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "TELEGRAM_IMAGE", "TELEGRAM_PDF", "TELEGRAM_TEXT", name="source", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("image_sha256", sa.String(length=64), nullable=True),
        sa.Column("order_id", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("grand_total_minor", sa.Integer(), nullable=False),
        sa.Column("unaccounted_adjustment_minor", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "reconciliation_outcome",
            sa.Enum(
                "BALANCED", "SKIPPED", "CLASS_2", name="reconciliationoutcome", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("occurred_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_on_local", sa.Date(), nullable=False),
        sa.Column(
            "date_source",
            sa.Enum("RECEIPT_PRINTED", "MESSAGE_TIMESTAMP", name="datesource", native_enum=False),
            nullable=False,
        ),
        sa.Column("related_transaction_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("currency = upper(currency)", name="ck_transactions_currency_upper"),
        sa.CheckConstraint("length(currency) = 3", name="ck_transactions_currency_len"),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_extraction_id"],
            ["raw_extractions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "image_sha256", name="uq_transactions_user_image"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_user_local_date", ["user_id", "occurred_on_local"], unique=False
        )
        batch_op.create_index(
            "ix_transactions_user_merchant", ["user_id", "merchant_id"], unique=False
        )

    op.create_table(
        "transaction_adjustments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("CHARGE", "TAX", "DISCOUNT", name="adjustmentkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_minor >= 0", name="ck_adjustments_amount_positive"),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id", "position", name="uq_adjustments_txn_position"),
    )
    with op.batch_alter_table("transaction_adjustments", schema=None) as batch_op:
        batch_op.create_index("ix_adjustments_user_kind", ["user_id", "kind"], unique=False)

    op.create_table(
        "transaction_line_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.String(length=400), nullable=False),
        sa.Column("quantity_text", sa.String(length=120), nullable=True),
        sa.Column("mrp_minor", sa.Integer(), nullable=True),
        sa.Column("line_total_minor", sa.Integer(), nullable=False),
        sa.Column("normalized_slug", sa.String(length=200), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("unit_normalized", sa.String(length=16), nullable=True),
        sa.Column("pack_count", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "mrp_minor IS NULL OR mrp_minor >= 0", name="ck_line_items_mrp_positive"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id", "position", name="uq_line_items_txn_position"),
    )
    with op.batch_alter_table("transaction_line_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_line_items_user_category", ["user_id", "category_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction_line_items", schema=None) as batch_op:
        batch_op.drop_index("ix_line_items_user_category")

    op.drop_table("transaction_line_items")
    with op.batch_alter_table("transaction_adjustments", schema=None) as batch_op:
        batch_op.drop_index("ix_adjustments_user_kind")

    op.drop_table("transaction_adjustments")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_user_merchant")
        batch_op.drop_index("ix_transactions_user_local_date")

    op.drop_table("transactions")
    with op.batch_alter_table("raw_extractions", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_extractions_user_hash")

    op.drop_table("raw_extractions")
    with op.batch_alter_table("merchants", schema=None) as batch_op:
        batch_op.drop_index("ix_merchants_user")

    op.drop_table("merchants")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("ix_categories_user")

    op.drop_table("categories")
    op.drop_table("users")
    # ### end Alembic commands ###
