"""pending receipts survive a restart

Revision ID: 6777f3118190
Revises: d18a6f40b3c5
Create Date: 2026-08-09 13:27:38.286673

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6777f3118190"
down_revision: str | Sequence[str] | None = "d18a6f40b3c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_extraction_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_on_local", sa.Date(), nullable=False),
        sa.Column(
            "date_source",
            sa.Enum("RECEIPT_PRINTED", "MESSAGE_TIMESTAMP", name="datesource", native_enum=False),
            nullable=False,
        ),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("merchant_slug", sa.String(length=80), nullable=True),
        sa.Column("gap_accepted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_extraction_id"],
            ["raw_extractions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash", name="uq_pending_receipts_key"),
    )
    with op.batch_alter_table("pending_receipts", schema=None) as batch_op:
        batch_op.create_index("ix_pending_receipts_user", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_receipts", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_receipts_user")

    op.drop_table("pending_receipts")
    # ### end Alembic commands ###
